### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

C:\Users\srini\AppData\Local\Temp\ipykernel_33740\2162656668.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv).

   ### Step 3. Assign each to a to a variable called cars1 and cars2

In [2]:
cars1 = pd.read_csv(r"C:\Users\srini\GenAI\GenAI\4-Week-AI-Training-main\AI\08-Pandas\05_Merge\Auto_MPG\cars1.csv")
cars2 = pd.read_csv(r"C:\Users\srini\GenAI\GenAI\4-Week-AI-Training-main\AI\08-Pandas\05_Merge\Auto_MPG\cars2.csv")

print(cars1.head())
print(cars2.head())

    mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  18.0          8           307        130    3504          12.0     70
1  15.0          8           350        165    3693          11.5     70
2  18.0          8           318        150    3436          11.0     70
3  16.0          8           304        150    3433          12.0     70
4  17.0          8           302        140    3449          10.5     70

   origin                        car  Unnamed: 9  Unnamed: 10  Unnamed: 11  \
0       1  chevrolet chevelle malibu         NaN          NaN          NaN
1       1          buick skylark 320         NaN          NaN          NaN
2       1         plymouth satellite         NaN          NaN          NaN
3       1              amc rebel sst         NaN          NaN          NaN
4       1                ford torino         NaN          NaN          NaN

   Unnamed: 12  Unnamed: 13
0          NaN          NaN
1          NaN          NaN
2          NaN          NaN
3          NaN          NaN
4          NaN          NaN
    mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  33.0          4            91         53    1795          17.4     76
1  20.0          6           225        100    3651          17.7     76
2  18.0          6           250         78    3574          21.0     76
3  18.5          6           250        110    3645          16.2     76
4  17.5          6           258         95    3193          17.8     76

   origin                 car
0       3         honda civic
1       1      dodge aspen se
2       1   ford granada ghia
3       1  pontiac ventura sj
4       1       amc pacer d/l

### Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

In [3]:
cars1 = cars1.loc[:, "mpg":"car"]
cars1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino

### Step 5. What is the number of observations in each dataset?

In [14]:
print(cars1.shape)
print(cars2.shape)

(198, 9)
(200, 9)

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [6]:
cars = pd.concat([cars1, cars2], ignore_index=True)
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97,52,2130,24.6,82,2,vw pickup
395,32.0,4,135,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120,79,2625,18.6,82,1,ford ranger
397,31.0,4,119,82,2720,19.4,82,1,chevy s-10

### Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [7]:
nr_owners = np.random.randint(15000, high=73001, size=398, dtype='l')
nr_owners

array([69908, 68658, 18226, 35525, 62331, 19075, 56435, 69757, 53388,
       50205, 49075, 55282, 39636, 49531, 40921, 28383, 57293, 22100,
       34609, 64200, 66476, 20557, 17752, 27571, 19709, 41627, 37016,
       59398, 63093, 51075, 53665, 28776, 36511, 69899, 51201, 24704,
       53173, 27587, 59140, 19847, 71627, 25728, 27541, 47428, 23247,
       28640, 39261, 65491, 64941, 40221, 41829, 58707, 22115, 52292,
       18827, 67333, 32477, 23677, 24730, 39838, 19228, 48964, 40252,
       65720, 39855, 44232, 38478, 36340, 20868, 26371, 36112, 60969,
       19787, 69819, 18758, 58126, 21271, 71841, 58007, 23696, 45256,
       35517, 38204, 28562, 18557, 61295, 70790, 31464, 42661, 20720,
       32881, 31938, 72658, 31180, 66102, 53530, 25320, 17388, 70259,
       35600, 67117, 55174, 38900, 26636, 29833, 68227, 67219, 58680,
       58051, 20986, 29429, 27433, 37995, 70005, 61452, 40267, 17977,
       50309, 72632, 40449, 64329, 50329, 22596, 67840, 38040, 30357,
       42952, 45360, 50489, 70759, 29790, 20769, 15172, 38062, 53306,
       29048, 43274, 34168, 67509, 70397, 64413, 67218, 30783, 16301,
       50354, 69260, 44308, 20802, 23774, 18807, 71338, 59229, 46735,
       42587, 31418, 65521, 36659, 32074, 52503, 17007, 29447, 17349,
       17370, 48736, 47799, 65986, 22494, 42546, 70502, 16503, 39636,
       26599, 66459, 30186, 55600, 27428, 30126, 63460, 26574, 70260,
       51082, 43136, 22630, 57662, 63107, 30251, 44847, 63693, 60324,
       42757, 41110, 59434, 45510, 19460, 27281, 23704, 64688, 60120,
       40102, 50563, 45590, 62575, 59043, 60291, 32031, 16682, 35007,
       23236, 26402, 30054, 48541, 66536, 59152, 63869, 40320, 35228,
       59645, 37390, 51845, 69809, 15541, 35705, 44872, 71625, 42026,
       29731, 44563, 59793, 39223, 69595, 26401, 38582, 70987, 41175,
       16796, 69091, 67989, 42647, 54192, 50235, 38960, 40150, 64261,
       15906, 70246, 40490, 27885, 59530, 21719, 56476, 21905, 19918,
       40966, 15229, 60591, 46492, 33645, 36833, 41471, 52054, 21725,
       37018, 48272, 33921, 69010, 16354, 24426, 65820, 24049, 51049,
       41003, 22108, 59461, 55294, 29666, 43541, 66613, 70686, 44595,
       16977, 41037, 62679, 36244, 55882, 54497, 69404, 17541, 48319,
       59905, 41672, 19885, 71320, 15622, 36071, 45736, 25533, 58843,
       66158, 40615, 43738, 27877, 65134, 22226, 30127, 46166, 61134,
       71570, 26528, 43425, 70321, 61895, 45943, 56603, 46109, 64950,
       45634, 61055, 64573, 63195, 57016, 50659, 52383, 35949, 26985,
       23696, 27518, 28900, 66144, 34147, 36168, 55270, 43074, 67119,
       29146, 50934, 22272, 52399, 46413, 51678, 31482, 60955, 69501,
       25263, 28493, 71813, 42329, 46715, 71722, 40628, 68405, 41422,
       44788, 41659, 59633, 26610, 21057, 45588, 23044, 17197, 18663,
       36107, 62657, 23442, 25727, 61339, 23057, 61722, 64795, 71804,
       56849, 44354, 48621, 68891, 40795, 25576, 63124, 26288, 55385,
       28607, 72134, 33516, 32464, 23996, 26968, 25806, 16641, 56025,
       48984, 17627, 70443, 64678, 56636, 58702, 23026, 63385, 36683,
       49892, 30368])

### Step 8. Add the column owners to cars

In [8]:
cars['owners'] = nr_owners
cars.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owners
393,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,23026
394,44.0,4,97,52,2130,24.6,82,2,vw pickup,63385
395,32.0,4,135,84,2295,11.6,82,1,dodge rampage,36683
396,28.0,4,120,79,2625,18.6,82,1,ford ranger,49892
397,31.0,4,119,82,2720,19.4,82,1,chevy s-10,30368