# Ex2 - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: 

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

C:\Users\srini\AppData\Local\Temp\ipykernel_18216\2162656668.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [7]:
# The local path to your downloaded file
file_path = r'C:\Users\srini\Downloads\4-Week-AI-Training-main\DAT8-master\DAT8-master\data\chipotle.tsv'

# Read the local file instead of the URL
chipo = pd.read_csv(file_path, sep='\t')

### Step 4. See the first 10 entries

In [9]:
chipo.count()

order_id              4622
quantity              4622
item_name             4622
choice_description    3376
item_price            4622
dtype: int64

### Step 5. What is the number of observations in the dataset?

In [10]:
# Solution 1

chipo.shape[0]  # entries <= 4622 observations

4622

In [5]:
# Solution 2

chipo.info() # entries <= 4622 observations

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
order_id              4622 non-null int64
quantity              4622 non-null int64
item_name             4622 non-null object
choice_description    3376 non-null object
item_price            4622 non-null object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB

### Step 6. What is the number of columns in the dataset?

In [12]:
chipo.shape

(4622, 5)

### Step 7. Print the name of all the columns.

In [13]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

### Step 8. How is the dataset indexed?

In [14]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Which was the most-ordered item?

In [15]:
c = chipo.groupby('item_name')
c = c.sum()
c = c.sort_values(['quantity'], ascending=False)
c.head(1)

,order_id,quantity,choice_description,item_price
item_name,,,,
Chicken Bowl,713926,761,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98 $10.98 $11.25 $8.75 $8.49 $11.25 $8.75 ...

### Step 10. For the most-ordered item, how many items were ordered?

In [10]:
c = chipo.groupby('item_name')
c = c.sum()
c = c.sort_values(['quantity'], ascending=False)
c.head(1)

              order_id  quantity
item_name
Chicken Bowl    713926       761

### Step 11. What was the most ordered item in the choice_description column?

In [16]:
c = chipo.groupby('choice_description').sum()
c = c.sort_values(['quantity'], ascending=False)
c.head(1)
# Diet Coke 159

,order_id,quantity,item_name,item_price
choice_description,,,,
[Diet Coke],123455,159,Canned SodaCanned SodaCanned Soda6 Pack Soft D...,$2.18 $1.09 $1.09 $6.49 $2.18 $1.25 $1.09 $6.4...

### Step 12. How many items were orderd in total?

In [17]:
total_items_orders = chipo.quantity.sum()
total_items_orders

4972

### Step 13. Turn the item price into a float

#### Step 13.a. Check the item price type

In [13]:
chipo.item_price.dtype

dtype('O')

#### Step 13.b. Create a lambda function and change the type of item price

In [18]:
dollarizer = lambda x: float(x[1:-1])
chipo.item_price = chipo.item_price.apply(dollarizer)

#### Step 13.c. Check the item price type

In [19]:
chipo.item_price.dtype

dtype('float64')

### Step 14. How much was the revenue for the period in the dataset?

In [20]:
revenue = (chipo['quantity']* chipo['item_price']).sum()

print('Revenue was: $' + str(np.round(revenue,2)))

Revenue was: $39237.02

### Step 15. How many orders were made in the period?

In [23]:
orders = chipo.order_id.value_counts().count()
orders

1834

### Step 16. What is the average revenue amount per order?

In [31]:
# Solution 1

chipo['revenue'] = chipo['quantity'] * chipo['item_price']
order_grouped = chipo.groupby(by=['order_id']).sum()
order_grouped.mean()['revenue']

21.394231188658654

In [32]:
# Solution 2

chipo.groupby('order_id')['revenue'].sum().mean()

21.394231188658654

### Step 17. How many different items are sold?

In [33]:
chipo.item_name.value_counts().count()

50